# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
    "npm ci"
]

[phases.build]
cmds = [
    "cd backend && npm install",
    "cd frontend && npm install && npm run build"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
PORT = "3001"
